---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: mediaservers
  remote_user: parmstro
  become: yes

  roles:
    - media

